import puppyParty from "../images/puppy-party.png";
import vaxTrax from "../images/vax-trax-landing.png";
import quizTime from "../images/quiz-time.png";
import weatherTravel from "../images/weather-travel.png";
import budgetTracker from "../images/budget-tracker.png";
import employeeDirectory from "../images/employee-directory.png";

const portfolioData = [
  {
    name: "Vax Trax",
    description:
      "A full stack web application for staying informed on Covid-19 data and sharing personal experience with vaccination using passport, sequelize, mysql, and more",
    image: vaxTrax,
    githubLink: "https://github.com/jacob-af/vax-trax",
    deployedLink: "https://vax-trax.herokuapp.com/"
  },
  {
    name: "Employee Directory",
    description:
      "A React based application for filtering and sorting employee data generated by the Random User API",
    image: employeeDirectory,
    githubLink: "https://github.com/jacob-af/employee-directory",
    deployedLink: "https://jacobaf.com/employee-directory/"
  },
  {
    name: "Budget Tracker",
    description:
      "A full stack web application for keeping track of income and expenses both on and off line using MongoDB, IndexedDB, a manifest.json and service-worker.",
    image: budgetTracker,
    githubLink: "https://github.com/jacob-af/budget-tracker",
    deployedLink: "https://budg3t-track3r.herokuapp.com/"
  },
  {
    name: "Weather Travel",
    description: "A colorful weather dashboard using the Open Weather API.",
    image: weatherTravel,
    githubLink: "https://github.com/jacob-af/weather-travel",
    deployedLink: "https://www.jacobaf.com/weather-travel/"
  },
  {
    name: "Puppy Party",
    description:
      "Schedule all your trips to the Dog Park using third party APIs, jQuery, and Materialze.css",
    image: puppyParty,
    githubLink: "https://github.com/jacob-af/Puppy-Party-Planner",
    deployedLink: "https://www.jacobaf.com/Puppy-Party-Planner/"
  },
  {
    name: "Quiz Time",
    description:
      "Timed quiz covering some JavaScript basics using jQuery and Bootstrap",
    image: quizTime,
    githubLink: "https://github.com/jacob-af/quiz-time",
    deployedLink: "https://www.jacobaf.com/quiz-time/"
  }
];

export default portfolioData;
